[package]
name = "flap-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
flap-lib = { path = "../flap-lib" }
tokio = { version = "1.47.1", features = ["rt", "macros"]}
